const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const mt=$('.menu-toggle'),gnb=$('.gnb');mt.addEventListener('click',()=>{const o=gnb.classList.toggle('open');mt.textContent=o?'×':'☰';mt.setAttribute('aria-expanded',o)});const quick=$('.quick');$('.quick-toggle').addEventListener('click',e=>{const c=quick.classList.toggle('closed');e.currentTarget.querySelector('span').textContent=c?'+':'×'});const chat=$('.chat'),setChat=o=>{chat.classList.toggle('open',o);chat.setAttribute('aria-hidden',!o)};$('.chat-launch').addEventListener('click',()=>setChat(!chat.classList.contains('open')));$('.chat header button').addEventListener('click',()=>setChat(false));$$('.questions button').forEach(b=>b.addEventListener('click',()=>{const p=document.createElement('p');p.textContent=b.dataset.answer;$('.answer').replaceChildren(p)}));if(window.gsap&&window.ScrollTrigger&&!matchMedia('(prefers-reduced-motion: reduce)').matches){gsap.registerPlugin(ScrollTrigger);$$('.reveal').forEach(e=>gsap.from(e,{scrollTrigger:{trigger:e,start:'top 88%',once:true},y:70,opacity:0,duration:1,ease:'power3.out'}));$$('.shake').forEach(e=>gsap.from(e,{scrollTrigger:{trigger:e,start:'top 90%',once:true},x:-20,opacity:0,duration:.9,ease:'elastic.out(1,.2)'}));const company=$('.company'),typeItems=$$('.type-text',company),companyButton=$('.type-cta',company),typing=gsap.timeline({scrollTrigger:{trigger:company,start:'top 72%',once:true}});typeItems.forEach((el,index)=>{const text=el.dataset.typeText||el.textContent.trim().replace(/\s+/g,' ');typing.set(el,{opacity:1,onComplete:()=>{el.textContent='';el.classList.add('typing')}}).to({count:0},{count:text.length,duration:Math.max(.45,text.length*.035),ease:'none',onUpdate:function(){el.textContent=text.slice(0,Math.ceil(this.targets()[0].count))},onComplete:()=>el.classList.remove('typing')},index?'>+.12':0)});typing.set(companyButton,{opacity:0}).to(companyButton,{opacity:1,duration:.18}).to(companyButton,{x:-16,duration:.1}).to(companyButton,{x:14,duration:.1}).to(companyButton,{x:-10,duration:.1}).to(companyButton,{x:7,duration:.1}).to(companyButton,{x:0,duration:.14,ease:'power2.out'});gsap.to('.hero-asset',{yPercent:10,scrollTrigger:{trigger:'.hero',scrub:1}})}

const newsData={
  notice:{more:'https://www.duzon119.co.kr/customer/notice.asp',items:[['[Amaranth10 Cloud] 더존 메일 스팸 차단 관련 안내','2026-04-30'],['[Amaranth10] PC메신저 서비스 전환 및 기술지원 안내','2026-03-26'],['[Bizbox Alpha] 보안 취약점 업데이트 권고 안내','2026-02-25'],['더존 솔루션 최신 업데이트 및 고객 안내','2025-12-15'],['서비스 점검 및 이용 안내','2025-11-28']]},
  amaranth:{more:'https://www.duzon119.co.kr/amaranth10/pds.asp',items:[['인사 담당자를 위한 교대근무 활용 프로세스 & TIP','2024-11-25'],['유연근무 관리 활용 프로세스 & TIP','2024-11-25'],['ONE AI 데이터 분석 활용 프로세스 & TIP','2024-11-25'],['ERP 관리자 모듈 환경설정 활용 TIP','2024-07-17'],['신규 입사자 관리 활용 프로세스','2024-07-17']]},
  bizbox:{more:'https://www.duzon119.co.kr/bizbox/pds.asp',items:[['Bizbox Alpha 메신저 설치 가이드','2024-07-07'],['전자결재 프로그램 설치 안내','2025-12-09'],['Bizbox Alpha 최신 버전 재배포 안내','2025-11-28'],['PC 메신저 보안 업데이트 안내','2025-10-20'],['모바일 앱 사용 가이드','2025-09-12']]},
  icube:{more:'https://www.duzon119.co.kr/icube/pds.asp',items:[['iCUBE 재설치 바로가기','2024-07-01'],['iCUBE G20 재설치 바로가기','2024-07-01'],['iCUBE 업데이트 설치 안내','2024-06-18'],['회계 모듈 활용 가이드','2024-05-22'],['인사·급여 모듈 활용 가이드','2024-04-11']]}
};
let newsSwiper;
function renderNews(category){const data=newsData[category],wrapper=$('.news-slider .swiper-wrapper');if(newsSwiper)newsSwiper.destroy(true,true);wrapper.replaceChildren(...data.items.map(([title,date])=>{const card=document.createElement('a');card.className='news-card glass swiper-slide';card.href=data.more;const img=document.createElement('img');img.src='assets/notice-thumb.png';img.alt=title;const badge=document.createElement('b');badge.textContent='NEW';const copy=document.createElement('p');copy.textContent=title;const time=document.createElement('time');time.textContent=date;card.append(img,badge,copy,time);return card}));$('.news-more').href=data.more;newsSwiper=new Swiper('.news-slider',{slidesPerView:'auto',spaceBetween:24,loop:true,speed:650,grabCursor:true,autoplay:{delay:2000,disableOnInteraction:false,pauseOnMouseEnter:true},scrollbar:{el:'.news-slider .swiper-scrollbar',draggable:true,snapOnRelease:true},keyboard:{enabled:true}})}
if(window.Swiper){renderNews('notice');$$('.news-tabs button').forEach(button=>button.addEventListener('click',()=>{$$('.news-tabs button').forEach(tab=>tab.classList.toggle('active',tab===button));renderNews(button.dataset.category)}))}
